import Link from "next/link";
import CompleteLessonButton from "@/components/CompleteLessonButton";
import Sticky from "@/components/Sticky";
import styles from "./page.module.css";

export default function Day08Lesson() {
  return (
    <>
      <Link href="/" className={styles.backLink}>
        ← ロードマップに戻る
      </Link>

      <h1 className={styles.title}>
        Day08: meta情報を設定する（タイトル・descriptionなど）
      </h1>

      <p className={styles.paragraph}>
        ブラウザのタブに表示されるページタイトルや、SNSでリンクを
        共有したときに出てくるカードの文言——これらはHTMLの
        <code>&lt;head&gt;</code>タグの中にある<strong>meta情報</strong>
        （メタデータ）で決まっています。今日は、Next.jsが用意している
        <strong>Metadata API</strong>を使って、この
        <code>&lt;head&gt;</code>の中身をどう設定するかを学びます。
      </p>

      <h2 className={styles.heading}>
        そもそも<code>&lt;head&gt;</code>って何？
      </h2>
      <p className={styles.paragraph}>
        HTMLのページは、大きく<code>&lt;head&gt;</code>と
        <code>&lt;body&gt;</code>
        の2つに分かれています。<code>&lt;body&gt;</code>は画面に
        実際に表示される部分（これまでDayで書いてきたJSXの中身）ですが、
        <code>&lt;head&gt;</code>は画面には表示されない、
        <strong>ページの情報</strong>を書く場所です。
      </p>
      <pre className={styles.codeBlock}>
        <code>{`<html>
  <head>
    <!-- 画面には表示されないが、ブラウザやSNS・検索エンジンが読む情報 -->
    <title>ページのタイトル</title>
    <meta name="description" content="ページの説明文" />
  </head>
  <body>
    <!-- ここが画面に表示される部分。これまでのDayで書いてきたJSX -->
  </body>
</html>`}</code>
      </pre>
      <p className={styles.paragraph}>
        <code>&lt;title&gt;</code>タグはブラウザのタブに表示される文字列、
        <code>&lt;meta name=&quot;description&quot;&gt;</code>
        は検索結果の見出しの下に表示される説明文、というように、
        それぞれのタグに役割があります。素のHTMLでは、これらのタグを 直接
        <code>&lt;head&gt;</code>の中に書きますが、Next.jsでは
        タグを直接書く代わりに、<strong>JavaScriptのオブジェクト</strong>
        として指定します。
      </p>

      <h2 className={styles.heading}>
        <code>metadata</code>オブジェクトの基本
      </h2>
      <p className={styles.paragraph}>
        <code>page.tsx</code>や<code>layout.tsx</code>から
        <code>metadata</code>という名前の変数を<strong>exportする</strong>
        だけで、Next.jsが自動的にそのページの
        <code>&lt;head&gt;</code>タグを組み立ててくれます。
      </p>
      <pre className={styles.codeBlock}>
        <code>{`import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "自己紹介ページ",
  description: "私のプロフィールを紹介するページです",
};

export default function Page() {
  return <h1>自己紹介</h1>;
}
// <head>に以下が自動で追加される
// <title>自己紹介ページ</title>
// <meta name="description" content="私のプロフィールを紹介するページです" />`}</code>
      </pre>
      <p className={styles.paragraph}>
        実はこのアプリの<code>app/layout.tsx</code>にも、すでに
        <code>metadata</code>が書かれています。
      </p>
      <pre className={styles.codeBlock}>
        <code>{`// app/layout.tsx（現状）
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};`}</code>
      </pre>
      <p className={styles.paragraph}>
        これは<code>create-next-app</code>
        でプロジェクトを作ったときに自動で入る初期値です。
        ブラウザでこのアプリのタブを見ると「Create Next App」と
        表示されているはずなので、確認してみてください。今日のお題では、
        この初期値をこのロードマップアプリに合った内容に変更します。
      </p>

      <h2 className={styles.heading}>
        <code>layout.tsx</code>と<code>page.tsx</code>、どちらに書く？
      </h2>
      <p className={styles.paragraph}>
        Day11で詳しく扱いますが、<code>layout.tsx</code>は
        「複数のページで共通の外枠」を作るファイルです。
        <code>metadata</code>もこの親子関係を引き継ぎ、
        <strong>
          <code>layout.tsx</code>に書けばアプリ全体（または配下の全ページ）
        </strong>
        に適用され、
        <strong>
          <code>page.tsx</code>に書けばそのページだけ
        </strong>
        に適用されます。ページ側で<code>metadata</code>
        を指定すれば、同じフィールド（<code>title</code>など）は
        レイアウト側の値を<strong>上書き</strong>します。
      </p>
      <pre className={styles.codeBlock}>
        <code>{`// app/layout.tsx（全ページ共通のデフォルト）
export const metadata: Metadata = {
  title: "自己紹介アプリ",
  description: "自己紹介アプリのトップページです",
};

// app/blog/page.tsx（このページだけ上書き）
export const metadata: Metadata = {
  title: "ブログ一覧",
  description: "投稿した記事の一覧ページです",
};
// /blog にアクセスすると <title>ブログ一覧</title> が使われる`}</code>
      </pre>

      <h2 className={styles.heading}>
        <code>title.template</code>でタブの表示を統一する
      </h2>
      <p className={styles.paragraph}>
        ページごとに毎回「サイト名」を書くのは面倒ですし、
        表記ゆれも起きやすいです。<code>layout.tsx</code>で<code>title</code>
        を文字列ではなく
        <strong>オブジェクト</strong>にして<code>template</code>
        を指定すると、子ページの<code>title</code>に
        自動でプレフィックス・サフィックスを付けられます。
      </p>
      <pre className={styles.codeBlock}>
        <code>{`// app/layout.tsx
export const metadata: Metadata = {
  title: {
    template: "%s | 自己紹介アプリ",
    default: "自己紹介アプリ", // titleを指定しないページで使われる
  },
};

// app/blog/page.tsx
export const metadata: Metadata = {
  title: "ブログ一覧",
};
// このページのタブには「ブログ一覧 | 自己紹介アプリ」と表示される`}</code>
      </pre>
      <p className={styles.paragraph}>
        <code>%s</code>の部分に、子ページで指定した
        <code>title</code>が差し込まれる、とイメージすると分かりやすいです。
        <code>template</code>を使う場合は、
        <strong>
          <code>default</code>を必ずセットで指定する
        </strong>
        必要がある点に注意してください（<code>title</code>も<code>default</code>
        も無いページで、テンプレートだけ 適用しようがないためです）。
      </p>

      <h2 className={styles.heading}>他によく使うフィールド</h2>
      <p className={styles.paragraph}>
        <code>title</code>・<code>description</code>以外にも、
        <code>Metadata</code>型にはたくさんのフィールドが用意されています。
        代表的なものをいくつか紹介します。
      </p>
      <pre className={styles.codeBlock}>
        <code>{`export const metadata: Metadata = {
  title: "自己紹介ページ",
  description: "私のプロフィールを紹介するページです",
  keywords: ["自己紹介", "プロフィール", "Next.js"],
  icons: {
    icon: "/icon.png", // ブラウザタブのファビコン
  },
  openGraph: {
    // X（Twitter）やLINE、Slackなどでリンクを貼ったときに
    // 表示されるカードの中身（OGP）
    title: "自己紹介ページ",
    description: "私のプロフィールを紹介するページです",
    images: ["/og-image.png"],
  },
};`}</code>
      </pre>
      <p className={styles.paragraph}>
        <code>openGraph</code>は「Open Graph Protocol」の略で、
        SNSでURLをシェアしたときに表示される、画像付きのリッチな
        カードを制御するための項目です。全部を一度に覚える必要はなく、
        「必要になったら<code>Metadata</code>型の候補から
        探せばよい」くらいの感覚で大丈夫です。
      </p>

      <h2 className={styles.heading}>
        検索エンジンへの指示：<code>robots</code>
      </h2>
      <p className={styles.paragraph}>
        「このページは検索結果に載せたくない」
        「このリンクはクロール（巡回）してほしくない」
        というように、検索エンジンのクローラーに向けた指示を出す 仕組みが
        <code>robots</code>です。Next.jsには、
        <strong>ページ単位</strong>と<strong>サイト全体</strong>の 2つのレベルで
        <code>robots</code>を設定する方法があります。
      </p>
      <p className={styles.paragraph}>
        1つ目は、<code>metadata</code>オブジェクトの
        <code>robots</code>フィールドです。特定のページだけを
        検索結果から除外したいときに使います。
      </p>
      <pre className={styles.codeBlock}>
        <code>{`// 会員限定ページなど、検索結果に出したくないページ
export const metadata: Metadata = {
  robots: {
    index: false, // このページを検索結果に載せない
    follow: false, // このページ内のリンクを辿らせない
  },
};
// <head>に <meta name="robots" content="noindex, nofollow" /> が追加される`}</code>
      </pre>
      <p className={styles.paragraph}>
        実は<code>robots</code>は、オブジェクトではなく
        <strong>文字列</strong>で書くこともできます。 出力される
        <code>&lt;meta&gt;</code>タグの中身と
        ほぼ同じ形で書けるので直感的ですが、タイプミスをしても
        TypeScriptがエラーを出してくれない点には注意してください。
      </p>
      <pre className={styles.codeBlock}>
        <code>{`export const metadata: Metadata = {
  robots: "noindex, nofollow",
};
// 上のオブジェクト形式とまったく同じ<meta>タグが出力される`}</code>
      </pre>
      <p className={styles.paragraph}>
        どちらの書き方でも結果は同じなので、
        <strong>
          プロパティ名の補完が効き、タイプミスにも気づける オブジェクト形式
        </strong>
        をこのレッスンではおすすめしますが、
        既存のコードで文字列形式を見かけても読めるようにしておきましょう。
      </p>
      <p className={styles.paragraph}>
        2つ目は、サイト全体に適用される<code>robots.txt</code>
        です。素のテキストファイルとして<code>app/robots.txt</code>
        に直接置くこともできますが、Next.jsでは
        <code>app/robots.ts</code>を作ると、そこから
        自動生成させることもできます。
      </p>
      <pre className={styles.codeBlock}>
        <code>{`// app/robots.ts
import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: "/admin/", // 管理画面などクロールされたくないパス
    },
    sitemap: "https://example.com/sitemap.xml",
  };
}
// http://localhost:3000/robots.txt にアクセスすると、
// User-Agent: * / Allow: / / Disallow: /admin/ ... が生成される`}</code>
      </pre>
      <p className={styles.paragraph}>
        つまり、
        <strong>
          「このページだけ」除外したいなら<code>metadata.robots</code>
        </strong>
        、
        <strong>
          「サイト全体でこのパス以下」を除外したいなら
          <code>app/robots.ts</code>
        </strong>
        、と使い分けます。
      </p>

      <h2 className={styles.heading}>
        <code>alternates</code>：正規URLと多言語ページ
      </h2>
      <p className={styles.paragraph}>
        同じ内容のページに複数のURLでアクセスできてしまう場合 （例：
        <code>?page=1</code>のようなクエリ付きURLと
        付いていないURL）、検索エンジンは「どちらが正式なURLか」
        を判断できず、SEO上不利になることがあります。
        <code>alternates.canonical</code>
        で「このURLが正式版です」と明示できます。
      </p>
      <pre className={styles.codeBlock}>
        <code>{`export const metadata: Metadata = {
  alternates: {
    canonical: "https://example.com/blog/my-post",
  },
};
// <head>に <link rel="canonical" href="https://example.com/blog/my-post" /> が追加される`}</code>
      </pre>
      <p className={styles.paragraph}>
        <code>alternates.languages</code>
        は、同じページの多言語版がある場合に、
        「日本語版はこちら、英語版はこちら」と検索エンジンへ
        伝えるためのものです。
      </p>
      <pre className={styles.codeBlock}>
        <code>{`export const metadata: Metadata = {
  alternates: {
    canonical: "https://example.com/ja",
    languages: {
      "en-US": "https://example.com/en",
      "ja-JP": "https://example.com/ja",
    },
  },
};`}</code>
      </pre>
      <p className={styles.paragraph}>
        このロードマップアプリのように、多言語対応をしない
        個人開発の練習用アプリでは、<code>canonical</code>
        だけ設定できれば十分なことがほとんどです。
      </p>

      <Sticky label="💬 ページによってタイトルを変えたいときは？">
        <p>
          ブログ記事のように「URLごとに中身（＝タイトル）が変わる」
          ページでは、静的な<code>metadata</code>オブジェクトの 代わりに
          <code>generateMetadata</code>という
          <strong>関数</strong>をexportします。中でデータを取得して、
          そのデータに応じた<code>title</code>を返す、という
          書き方です。今日は「固定のmeta情報を設定する」ところまでを
          扱い、動的な<code>generateMetadata</code>は、動的ルート （
          <code>[id]</code>）を学ぶDay25以降であらためて触れます。
        </p>
      </Sticky>

      <h2 className={styles.heading}>
        <code>&lt;head&gt;</code>タグを直接書いてはいけない
      </h2>
      <p className={styles.paragraph}>
        JSXの中に<code>&lt;title&gt;</code>や<code>&lt;meta&gt;</code>
        タグを直接書きたくなるかもしれませんが、App Routerでは
        <strong>使わないでください</strong>。 代わりに必ず<code>metadata</code>
        オブジェクト（または
        <code>generateMetadata</code>関数）を使います。
      </p>
      <pre className={styles.codeBlock}>
        <code>{`// ❌ JSXの中に直接タグを書くのは非推奨
export default function Page() {
  return (
    <>
      <title>自己紹介ページ</title>
      <h1>自己紹介</h1>
    </>
  );
}

// ✅ metadataオブジェクトを使う
export const metadata: Metadata = {
  title: "自己紹介ページ",
};

export default function Page() {
  return <h1>自己紹介</h1>;
}`}</code>
      </pre>
      <p className={styles.paragraph}>
        <code>metadata</code>オブジェクトを使うと、Next.jsが
        親子のレイアウトから情報をまとめて、重複のない正しい
        <code>&lt;head&gt;</code>を組み立ててくれます。タグを
        直接書いてしまうと、この仕組みの恩恵が受けられなくなります。
      </p>

      <h2 className={styles.heading}>
        例外：<strong>JSON-LD</strong>は<code>&lt;script&gt;</code>
        タグを直接書く
      </h2>
      <p className={styles.paragraph}>
        直前で「<code>&lt;head&gt;</code>タグは直接書かない」 と説明しましたが、
        <strong>JSON-LD</strong>（構造化データ） だけは例外で、JSXの中に
        <code>&lt;script&gt;</code>
        タグを直接書きます。JSON-LDとは、
        「このページは商品ページで、名前は〇〇、価格は△△円」
        のように、ページの内容を検索エンジンやAIに機械可読な
        形で伝えるためのデータ形式です。
      </p>
      <pre className={styles.codeBlock}>
        <code>{`export default async function Page() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Person",
    name: "太郎",
    jobTitle: "エンジニア",
  };

  return (
    <section>
      {/* JSON-LDはmetadataではなく、scriptタグを直接書く */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c"),
        }}
      />
      <h1>太郎の自己紹介</h1>
    </section>
  );
}`}</code>
      </pre>
      <p className={styles.paragraph}>
        <code>@type</code>には<code>Person</code>・<code>Product</code>・
        <code>Recipe</code>・<code>Event</code>など、
        <a href="https://schema.org/" target="_blank" rel="noreferrer">
          schema.org
        </a>
        で定義された「型」を指定します。<code>JSON.stringify</code>
        した文字列をそのまま<code>&lt;script&gt;</code>タグに
        差し込みたいので、通常の<code>{"{}"}</code>ではなく
        <code>dangerouslySetInnerHTML</code>
        という少し特殊な書き方を使います。
      </p>
      <p className={styles.paragraph}>
        <code>replace(/&lt;/g, &quot;\\u003c&quot;)</code>
        の部分は、ユーザーの入力データなどを
        <code>jsonLd</code>に含める場合に備えたセキュリティ対策です。
        <code>&lt;</code>をそのまま出力すると、
        悪意のあるスクリプトが埋め込まれてしまう可能性がある （
        <strong>XSS</strong>という攻撃手法です）ため、
        文字コード表記に置き換えてから出力しています。
      </p>

      <h2 className={styles.heading}>
        よく使われる例：パンくずリスト（<code>BreadcrumbList</code>）
      </h2>
      <p className={styles.paragraph}>
        JSON-LDの中でも定番の使い方が、
        <strong>パンくずリスト</strong>（ 「ロードマップ &gt;
        Day08」のような、今いる場所を示す ナビゲーション）を
        <code>BreadcrumbList</code>型で 表現するものです。検索結果にページ階層が
        そのまま表示されるようになることがあります。
      </p>
      <pre className={styles.codeBlock}>
        <code>{`export default function Page() {
  const breadcrumbJsonLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "ロードマップ",
        item: "https://example.com/",
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "Day08 練習ページ",
        item: "https://example.com/practice/day-08",
      },
    ],
  };

  return (
    <section>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(breadcrumbJsonLd).replace(/</g, "\\u003c"),
        }}
      />
      {/* ...ページの中身 */}
    </section>
  );
}`}</code>
      </pre>
      <p className={styles.paragraph}>
        <code>itemListElement</code>の配列に、階層の浅い方（
        <code>position: 1</code>）から順に並べていくのがポイントです。
        このロードマップアプリでも、各Dayのページ上部にある 「←
        ロードマップに戻る」というリンクは、 まさに「ロードマップ &gt;
        DayXX」という階層構造を
        表しているので、このパンくずの考え方がそのまま当てはまります。
      </p>

      <h2 className={styles.heading}>補足：Server Componentでのみ使える</h2>
      <p className={styles.paragraph}>
        <code>metadata</code>オブジェクトと<code>generateMetadata</code>
        関数は、<strong>Server Component</strong>
        （Day14で扱う、既定の状態のコンポーネント）でしか
        exportできません。ファイルの先頭に<code>&quot;use client&quot;</code>
        が付いているコンポーネントからはexportできない点だけ、
        頭の片隅に置いておいてください。
      </p>

      <h2 className={styles.heading}>まとめ</h2>
      <ul className={styles.list}>
        <li>
          ブラウザのタブに出るタイトルや、SNSでシェアされたときの
          カードの文言は、HTMLの<code>&lt;head&gt;</code>
          にあるmeta情報で決まる
        </li>
        <li>
          Next.jsでは<code>&lt;head&gt;</code>タグを直接書く代わりに、
          <code>page.tsx</code>や<code>layout.tsx</code>から
          <code>metadata</code>オブジェクトをexportする
        </li>
        <li>
          <code>layout.tsx</code>のmetadataはアプリ（または配下） 全体に、
          <code>page.tsx</code>のmetadataはそのページだけに
          適用される。同じフィールドは<code>page.tsx</code>側が 優先される
        </li>
        <li>
          <code>title</code>を
          <code>{`{ template: "%s | サイト名", default: "サイト名" }`}</code>
          の形にすると、子ページのタイトルに自動でサイト名を 付け足せる
        </li>
        <li>
          <code>description</code>・<code>keywords</code>・<code>icons</code>・
          <code>openGraph</code>など、 用途に応じたフィールドが
          <code>Metadata</code>型に 用意されている
        </li>
        <li>
          検索エンジン向けの指示は、ページ単位なら
          <code>metadata.robots</code>、サイト全体なら
          <code>app/robots.ts</code>と使い分ける
        </li>
        <li>
          <code>alternates.canonical</code>で正式なURLを、
          <code>alternates.languages</code>で多言語版のURLを
          検索エンジンに伝えられる
        </li>
        <li>
          JSON-LD（構造化データ）だけは例外で、
          <code>metadata</code>ではなく
          <code>&lt;script type=&quot;application/ld+json&quot;&gt;</code>
          タグを直接書く
        </li>
        <li>
          <code>metadata</code>・<code>generateMetadata</code>は Server
          Componentでのみexportできる
        </li>
      </ul>

      <div className={styles.taskBox}>
        <span className={styles.taskLabel}>本日のお題</span>
        <p className={styles.paragraph}>次の2つに取り組んでみましょう。</p>
        <ol className={styles.list}>
          <li>
            <code>app/layout.tsx</code>の<code>metadata</code>
            を、初期値の「Create Next App」から、このロードマップ アプリに合った
            <code>title</code>と<code>description</code>に書き換える
          </li>
          <li>
            <code>app/practice/day-08/page.tsx</code>を作り、 そのページだけの
            <code>metadata</code>
            （自分の名前を入れたタイトルなど）を設定する
          </li>
        </ol>
        <p className={styles.hint}>
          <code>http://localhost:3000/practice/day-08</code>{" "}
          で開けるようにしてください。
        </p>
        <p className={styles.paragraph}>
          （発展）余裕があれば、<code>app/practice/day-08/page.tsx</code>に、
          「ロードマップ」→「Day08 練習ページ」という2階層の
          <strong>パンくずリスト</strong>を表す
          <code>BreadcrumbList</code>のJSON-LDを、上の例を参考に
          <code>&lt;script type=&quot;application/ld+json&quot;&gt;</code>
          タグとして追加してみましょう。（BreadcrumbListのJSON-LDの書き方は検索してください）
        </p>
      </div>

      <h2 className={styles.heading}>確認方法</h2>
      <ol className={styles.list}>
        <li>
          ターミナルで <code>npm run dev</code> を実行してアプリを起動する
        </li>
        <li>
          ブラウザで<code>http://localhost:3000/</code>
          を開き、タブに表示されているタイトルが変わっていることを確認する
        </li>
        <li>
          続けて<code>http://localhost:3000/practice/day-08</code>
          を開き、タブのタイトルが<code>practice/day-08</code>
          固有のものに変わっていることを確認する
        </li>
        <li>
          デベロッパーツールの「Elements」タブなどで
          <code>&lt;head&gt;</code>を開き、<code>&lt;title&gt;</code>や
          <code>&lt;meta name=&quot;description&quot;&gt;</code>
          が意図通りの中身になっていればクリア🎉
        </li>
      </ol>

      <h2 className={styles.heading}>詰まったら</h2>
      <ul className={styles.list}>
        <li>
          タイトルが変わらないときは、<code>metadata</code>を
          <code>export const</code>で書けているか（
          <code>export default</code>と間違えていないか）確認する
        </li>
        <li>
          <code>metadata</code>は関数コンポーネントの<strong>外側</strong>
          にexportする必要があります。コンポーネントの中に書いてしまうと
          反映されません
        </li>
        <li>
          ファイルの先頭に<code>&quot;use client&quot;</code>
          が付いていないか確認する（付いているとmetadataをexportできません）
        </li>
        <li>
          <code>title.template</code>を使う場合は、
          <code>default</code>も一緒に指定できているか確認する
        </li>
        <li>保存を忘れていないか確認する（Cmd+S / Ctrl+S）</li>
      </ul>

      <CompleteLessonButton day={8} nextDay={9} />
    </>
  );
}
